import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./layout/header/page";
import Providers from "@/redux/Provider";
import FooterWeb from "./layout/footer/FooterWeb";
import ProviderReactQuery from "@/common/providers/react-query.provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Medi Fast Links",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className} id="checkout">
        <Providers>
          <ProviderReactQuery>
            <Header />
            <div>{children}</div>
            <FooterWeb />
          </ProviderReactQuery>
        </Providers>
      </body>
    </html>
  );
}
