import { comfortaa } from "@/fonts/font";
import Providers from "@/redux/Provider";
import type { Metadata } from "next";
import "./globals.css";
import FooterWeb from "./layout/footer/FooterWeb";
import Header from "./layout/header/page";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={comfortaa.className}>
        <Providers>
          <Header />
          {children}
          <FooterWeb />
        </Providers>
      </body>
    </html>
  );
}
